### ISSUE TITLE
EULER ANGLES IN REPOIMU

### ISSUE THREAD

**Issue by logindiamant** [agnieszkaszczesna/RepoIMU#1]
Dear colleagues, please tell us, how to calculate Euler angles from quaternion in RepoIMU datasets? May be you have some MATLAB script?

**Comment by agnieszkaszczesna** [comment]
You can use **_quat2eul_** function in Matlab.

**Comment by logindiamant** [comment]
Thanks, @agnieszkaszczesna 
I try to use SIMULINK block Quaternions to Rotation Angles
https://www.mathworks.com/help/aeroblks/quaternionstorotationangles.html
But I don't know what Rotation order right
ZYX | ZYZ |ZXY | ZXZ | YXZ | YXY | YZX | YZY | XYZ | XYX | XZY | XZX

And besides, it's not clear which coordinate system you are using NED or ENU?

![Снимок экрана (1308)](https://github.com/agnieszkaszczesna/RepoIMU/assets/39023197/91eeaa4d-7a82-4501-bc4b-1a6c4fe64ad5)

**Comment by agnieszkaszczesna** [comment]
Quaternions are free of coordinate systems. You can choose any that suits your application.

Sensor data was recorded in the XYZ convention and NEU. The signals have been oriented to the optical mocap system reference system for easy comparison. In the publication, you will find a detailed description - https://link.springer.com/chapter/10.1007/978-3-319-46418-3_45

**Comment by PeterBorisenko** [comment]
> NEU

Is the reference frame left-handed?

**Comment by agnieszkaszczesna** [comment]
The east, north, up (ENU) (and also north, east, down (NED)) coordinates are a right-handed coordinate system.

**Comment by PeterBorisenko** [comment]
> The east, north, up (ENU) (and also north, east, down (NED)) coordinates are a right-handed coordinate system.

That's why I am asking about the mentioned earlier NEU coordinate system. I assume that it was a typo.
