### ISSUE TITLE
Magnetic reference / dip

### ISSUE THREAD

**Issue by PeterBorisenko** [agnieszkaszczesna/RepoIMU#2]
Please tell us what the magnetic reference at which magnetometer readings were recorded.

**Comment by agnieszkaszczesna** [comment]
The reference vectors for estimation filters are Earth gravity vector g =
[0, 0,−9.81]T and magnetic north vector mg = [cos(L), 0, − sin(L)]^T , where L
is the geographical latitude angle. For the geographical position of the laboratory
(geographic coordinates: 50.35363, 18.9148285), where measurements were
done, we have L = 66deg = 1.1519 rad. Reference normalized vectors (length=1) were used to estimate the orientation.

See also [here ](https://www.mdpi.com/1424-8220/17/3/612), chapter 3.

**Comment by PeterBorisenko** [comment]
Thank you!
